# Generated by Django 5.0.2 on 2024-03-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingMediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, default='branding_media_images/default.jpg', null=True, upload_to='branding_media_images')),
                ('prompt_text', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branding_ai.brandingcategories')),
            ],
        ),
    ]
